drop table if exists member CASCADE;
create table member
(
    member_id Long generated by default as identity,
    member_name varchar(10),
    login_id varchar(10),
    password varchar(10),
    primary key (member_id)
);

drop table if exists item CASCADE;
create table item
(
    item_id bigint generated by default as identity,
    item_name varchar(10),
    price integer,
    seller varchar(10),
    regi_date timestamp,
    primary key (item_id)
);